name: Deploy Javadoc

on: [workflow_dispatch]

jobs:
  javadoc:
    if: ${{ github.repository_owner == 'saicone' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build javadoc with Gradle
        run: gradle allJavadoc
        shell: bash

      - name: Deploy javadoc to Github repository
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: build/docs/all-javadoc
          ssh-key: ${{ secrets.JAVADOC_DEPLOY_KEY }}
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          repository-name: saicone/javadoc
          branch: gh-pages
          target-folder: settings